import { ArrowUpRight, CalendarDays, CheckCircle2 } from 'lucide-react'
import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { AnimatedNumber, Reveal } from './Motion'

export default function HeroCard({ membership }) {
  const current = membership || { plan: 'No Active Membership', status: 'No membership', days_remaining: 0, renewal_date: null, progress: 0 }
  return <Reveal as="section" className="relative overflow-hidden rounded-2xl bg-ink p-6 text-white shadow-[0_24px_70px_rgba(18,18,18,0.16)] transition-shadow duration-300 hover:shadow-[0_28px_80px_rgba(18,18,18,0.22)] sm:p-8 lg:p-10"><div className="absolute -right-20 -top-28 h-72 w-72 rounded-full bg-accent/15 blur-3xl" /><div className="absolute bottom-0 right-16 h-40 w-40 rounded-full border-[28px] border-white/[0.03]" /><div className="relative"><div className="flex flex-col gap-7 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-accent">Current membership</p><h2 className="mt-3 font-heading text-4xl uppercase tracking-wide sm:text-5xl">{current.plan}</h2></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-accent/30 bg-accent/10 px-3 py-1.5 text-xs font-bold text-accent"><CheckCircle2 size={14} />{current.status}</span></div><div className="mt-10 grid gap-6 sm:grid-cols-2"><div><p className="text-xs text-white/55">Days remaining</p><p className="mt-1 text-4xl font-bold tracking-tight"><AnimatedNumber value={current.days_remaining} /></p></div><div className="flex items-start gap-3"><CalendarDays size={18} className="mt-1 text-accent" /><div><p className="text-xs text-white/55">Renewal date</p><p className="mt-1 text-sm font-semibold">{current.renewal_date || '—'}</p></div></div></div><div className="mt-8 max-w-2xl"><div className="flex items-center justify-between text-xs text-white/60"><span>Membership progress</span><span>{current.progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><Reveal className="h-full rounded-full bg-accent" delay={0.2} amount={0.5}><div className="h-full rounded-full bg-accent" style={{ width: `${current.progress}%` }} /></Reveal></div></div><Link to="/member/membership" className="group mt-8 inline-flex items-center gap-2 rounded-xl bg-accent px-5 py-3 text-sm font-bold text-ink transition hover:bg-white"><motion.span whileHover={{ scale: 1.02 }} transition={{ duration: 0.25 }}>View membership</motion.span><motion.span whileHover={{ x: 4 }} transition={{ duration: 0.25 }}><ArrowUpRight size={16} /></motion.span></Link></div></Reveal>
}
