import { motion } from 'framer-motion'
import { ArrowUpRight, CalendarDays, CheckCircle2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { dashboardMembership } from './DashboardData'
import { Reveal } from './Motion'

export default function MembershipSummary() {
  return <Reveal as="section" className="rounded-2xl border border-ink/10 bg-white p-6 shadow-[0_16px_50px_rgba(18,18,18,0.04)] transition-shadow duration-300 hover:shadow-[0_20px_55px_rgba(18,18,18,0.08)] sm:p-7"><div className="flex items-center justify-between"><div><p className="section-kicker text-ink/45">At a glance</p><h2 className="mt-2 font-heading text-3xl uppercase text-ink">Membership summary</h2></div><CheckCircle2 className="text-ink" size={21} /></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><p className="text-xs text-ink/50">Plan</p><p className="mt-1 text-sm font-bold text-ink">{dashboardMembership.plan}</p></div><div><p className="text-xs text-ink/50">Payment status</p><p className="mt-1 inline-flex items-center gap-1.5 text-sm font-bold text-ink"><CheckCircle2 size={15} className="text-ink" /> Paid</p></div><div><p className="text-xs text-ink/50">Expiration</p><p className="mt-1 flex items-center gap-2 text-sm font-semibold text-ink"><CalendarDays size={15} className="text-ink/40" />{dashboardMembership.renewalDate}</p></div><div><p className="text-xs text-ink/50">Remaining days</p><p className="mt-1 text-sm font-bold text-ink">{dashboardMembership.daysRemaining} days</p></div></div><motion.div whileHover={{ scale: 1.02 }} transition={{ duration: 0.25 }} className="mt-7 inline-flex"><Link to="/member/membership" className="group inline-flex items-center gap-2 rounded-xl border border-ink/10 px-4 py-3 text-sm font-bold text-ink transition hover:border-accent hover:bg-accent">Renew membership <motion.span whileHover={{ x: 4 }} transition={{ duration: 0.25 }}><ArrowUpRight size={16} /></motion.span></Link></motion.div></Reveal>
}
