import { Plus, Search } from 'lucide-react'
import Button from '../../../components/common/Button'
import { labelForStatus, labelForType, maintenanceStatuses, maintenanceTypes } from './maintenanceUtils'

function SelectFilter({ label, value, onChange, options, labels }) {
  return <select value={value} onChange={(event) => onChange(event.target.value)} aria-label={label} className="h-11 w-full rounded-2xl border border-ink/10 bg-white px-4 text-sm font-medium text-ink outline-none transition focus:border-accent"><option value="all">{label}</option>{options.map((option) => <option key={option} value={option}>{labels(option)}</option>)}</select>
}

export default function MaintenanceFilters({ search, filters, equipment, onSearchChange, onFilterChange, onAdd }) {
  return <div className="rounded-3xl border border-ink/10 bg-white p-5 shadow-[0_18px_60px_rgba(18,18,18,0.05)] sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-ink/45">Admin workspace</p><h1 className="mt-2 font-heading text-4xl uppercase tracking-wide text-ink">Maintenance</h1><p className="mt-2 max-w-xl text-sm leading-6 text-ink/60">Track and review equipment maintenance records.</p></div><Button type="button" onClick={onAdd} className="h-11 whitespace-nowrap"><Plus size={16} /> Add Maintenance</Button></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-[minmax(220px,1.5fr)_minmax(190px,1fr)_minmax(180px,1fr)_minmax(180px,1fr)_150px_150px]"><label className="relative block"><span className="sr-only">Search equipment or maintenance</span><Search size={17} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-ink/40" /><input value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search equipment or maintenance" className="h-11 w-full rounded-2xl border border-ink/10 bg-white pl-11 pr-4 text-sm text-ink outline-none transition focus:border-accent" /></label><select value={filters.equipment_id} onChange={(event) => onFilterChange('equipment_id', event.target.value)} aria-label="Filter by Equipment" className="h-11 w-full rounded-2xl border border-ink/10 bg-white px-4 text-sm font-medium text-ink outline-none transition focus:border-accent"><option value="all">All Equipment</option>{equipment.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.asset_code})</option>)}</select><SelectFilter label="All Types" value={filters.maintenance_type} onChange={(value) => onFilterChange('maintenance_type', value)} options={maintenanceTypes} labels={labelForType} /><SelectFilter label="All Statuses" value={filters.status} onChange={(value) => onFilterChange('status', value)} options={maintenanceStatuses} labels={labelForStatus} /><label><span className="sr-only">Date From</span><input type="date" value={filters.date_from} onChange={(event) => onFilterChange('date_from', event.target.value)} aria-label="Maintenance date from" className="h-11 w-full rounded-2xl border border-ink/10 bg-white px-4 text-sm text-ink outline-none transition focus:border-accent" /></label><label><span className="sr-only">Date To</span><input type="date" value={filters.date_to} min={filters.date_from || undefined} onChange={(event) => onFilterChange('date_to', event.target.value)} aria-label="Maintenance date to" className="h-11 w-full rounded-2xl border border-ink/10 bg-white px-4 text-sm text-ink outline-none transition focus:border-accent" /></label></div></div>
}
