import { CalendarCheck, Clock3, LogIn } from 'lucide-react'
import { formatDuration, formatTrendDate } from './dashboardUtils'

export default function AttendanceOverview({ statistics = {}, summary = {}, trend = [] }) {
  const max = Math.max(...trend.map((item) => Number(item.count ?? 0)), 1)
  return <section className="rounded-3xl border border-ink/10 bg-white p-6 shadow-[0_18px_60px_rgba(18,18,18,0.05)] sm:p-7"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent"><CalendarCheck size={18} /></span><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-ink/40">Attendance</p><h2 className="mt-1 font-heading text-2xl uppercase text-ink">Gym activity</h2></div></div><div className="mt-7 grid gap-4 sm:grid-cols-3"><Metric icon={LogIn} label="Today" value={statistics.today ?? summary.today_attendance ?? 0} /><Metric icon={CalendarCheck} label="This month" value={statistics.this_month ?? 0} /><Metric icon={Clock3} label="Average visit" value={formatDuration(statistics.average_visit_duration_seconds)} /></div><div className="mt-8"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[0.16em] text-ink/40">Last 7 days</p><p className="text-xs text-ink/40">Visits by Manila date</p></div><div className="mt-5 flex h-32 items-end gap-2 sm:gap-3">{trend.map((item) => <div key={item.date} className="flex min-w-0 flex-1 flex-col items-center gap-2"><div className="flex h-24 w-full items-end"><div className="w-full rounded-t-lg bg-accent transition-all" style={{ height: `${Math.max((Number(item.count ?? 0) / max) * 100, item.count ? 8 : 2)}%` }} title={`${item.count ?? 0} visits`} /></div><span className="truncate text-[10px] text-ink/45">{formatTrendDate(item.date)}</span></div>)}</div></div></section>
}

function Metric({ icon: Icon, label, value }) { return <div className="rounded-2xl bg-ink/[0.03] p-4"><Icon size={16} className="text-ink/40" /><p className="mt-3 text-xs text-ink/45">{label}</p><p className="mt-1 truncate text-lg font-bold text-ink">{value}</p></div> }
