import { Edit3, Eye, PauseCircle, PlayCircle } from 'lucide-react'
import { motion } from 'framer-motion'

const statusStyles = { active: 'border-emerald-500/20 bg-emerald-500/10 text-emerald-700', inactive: 'border-slate-500/20 bg-slate-500/10 text-slate-700' }
const formatPrice = (price) => Number(price ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })

export default function PlanTable({ plans, onView, onEdit, onToggleStatus, statusUpdatingId }) {
  return <div className="overflow-hidden rounded-3xl border border-ink/10 bg-white shadow-[0_18px_60px_rgba(18,18,18,0.06)]"><div className="overflow-x-auto"><table className="min-w-[980px] w-full border-separate border-spacing-0"><thead className="bg-[#fbfbf9]"><tr>{['Plan', 'Description', 'Duration', 'Price', 'Memberships', 'Status', 'Actions'].map((column) => <th key={column} className="px-4 py-4 text-left text-[11px] font-bold uppercase tracking-[0.24em] text-ink/45">{column}</th>)}</tr></thead><tbody>{plans.map((plan, index) => { const updating = statusUpdatingId === plan.id; return <motion.tr key={plan.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.3, delay: Math.min(index * 0.04, 0.2) }} className="border-t border-ink/5 text-sm text-ink/80 hover:bg-ink/[0.02]"><td className="px-4 py-4"><p className="font-semibold text-ink">{plan.name}</p><p className="mt-1 text-xs text-ink/45">{plan.slug}</p></td><td className="max-w-80 px-4 py-4"><p className="line-clamp-2 text-ink/65">{plan.description || '—'}</p></td><td className="px-4 py-4 whitespace-nowrap font-semibold text-ink">{plan.duration_days} days</td><td className="px-4 py-4 whitespace-nowrap font-semibold text-ink">{formatPrice(plan.price)}</td><td className="px-4 py-4 font-semibold text-ink">{plan.memberships_count ?? 0}</td><td className="px-4 py-4"><span className={`inline-flex rounded-full border px-3 py-1 text-xs font-bold uppercase tracking-[0.2em] ${statusStyles[plan.status] || 'border-ink/10 bg-ink/5 text-ink/60'}`}>{plan.status || 'Unknown'}</span></td><td className="px-4 py-4"><div className="flex items-center justify-end gap-2"><button type="button" onClick={() => onView(plan)} aria-label={`View ${plan.name}`} className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-ink/10 text-ink/60 transition hover:border-accent hover:text-ink"><Eye size={16} /></button><button type="button" onClick={() => onEdit(plan)} aria-label={`Edit ${plan.name}`} className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-ink/10 text-ink/60 transition hover:border-accent hover:text-ink"><Edit3 size={16} /></button><button type="button" onClick={() => onToggleStatus(plan)} disabled={updating} aria-label={`${plan.status === 'active' ? 'Deactivate' : 'Activate'} ${plan.name}`} className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-ink/10 text-ink/60 transition hover:border-accent hover:text-ink disabled:cursor-not-allowed disabled:opacity-40">{plan.status === 'active' ? <PauseCircle size={16} /> : <PlayCircle size={16} />}</button></div></td></motion.tr> })}</tbody></table></div></div>
}
