import { ArrowUpRight, Check, Clock3, CreditCard, Dumbbell, Flame, MoreHorizontal, ShieldCheck, UserRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { attendanceSummary, memberProfile, membership, recentActivity } from '../memberData'

export function PageIntro({ eyebrow, title, description, action }) { return <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="section-kicker text-ink/45">{eyebrow}</p><h2 className="mt-2 font-heading text-4xl uppercase leading-none tracking-wide text-ink sm:text-5xl">{title}</h2>{description && <p className="mt-4 max-w-2xl text-sm leading-6 text-ink/55">{description}</p>}</div>{action}</div> }

export function StatCard({ icon: Icon, label, value, detail }) { return <div className="rounded-2xl border border-ink/10 bg-white p-5 shadow-[0_16px_50px_rgba(18,18,18,0.05)]"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent/15 text-ink"><Icon size={19} strokeWidth={1.8} /></span><ArrowUpRight size={17} className="text-ink/25" /></div><p className="mt-6 text-xs font-semibold uppercase tracking-[0.16em] text-ink/40">{label}</p><p className="mt-1 text-2xl font-bold text-ink">{value}</p><p className="mt-1 text-xs text-ink/45">{detail}</p></div> }

export function MembershipCard({ compact = false }) { return <div className="relative overflow-hidden rounded-2xl bg-ink p-6 text-white shadow-[0_20px_70px_rgba(18,18,18,0.18)] sm:p-8"><div className="absolute -right-14 -top-20 h-48 w-48 rounded-full bg-accent/15 blur-2xl" /><div className="relative"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-accent">Current membership</p><h3 className="mt-3 font-heading text-3xl uppercase tracking-wide">{membership.plan}</h3></div><span className="rounded-full border border-accent/30 bg-accent/10 px-3 py-1 text-xs font-bold text-accent">{membership.status}</span></div><div className="mt-8 grid grid-cols-2 gap-5 border-t border-white/10 pt-5"><div><p className="text-xs text-white/45">Days remaining</p><p className="mt-1 text-3xl font-bold">{membership.daysRemaining}</p></div><div><p className="text-xs text-white/45">Renews on</p><p className="mt-2 text-sm font-semibold">{membership.renews}</p></div></div>{!compact && <><div className="mt-7 flex items-center justify-between text-xs text-white/50"><span>Membership progress</span><span>{membership.progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-accent" style={{ width: `${membership.progress}%` }} /></div></>}</div></div> }

export function ActivityList() { return <div className="divide-y divide-ink/10">{recentActivity.map((item) => <div key={item.label} className="flex items-center gap-4 py-4 first:pt-0 last:pb-0"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${item.tone === 'accent' ? 'bg-accent text-ink' : item.tone === 'dark' ? 'bg-ink text-accent' : 'bg-ink/5 text-ink'}`}><Check size={17} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-ink">{item.label}</p><p className="mt-1 text-xs text-ink/45">{item.detail}</p></div><span className="text-xs font-semibold text-ink/55">{item.value}</span></div>)}</div> }

export function QuickActions() { const actions = [{ label: 'View membership', path: '/member/membership', icon: ShieldCheck }, { label: 'See attendance', path: '/member/attendance', icon: CalendarIcon }, { label: 'Payment history', path: '/member/payments', icon: CreditCard }]; return <div className="grid gap-3 sm:grid-cols-3">{actions.map(({ label, path, icon: Icon }) => <Link key={path} to={path} className="group rounded-2xl border border-ink/10 bg-white p-4 shadow-[0_16px_50px_rgba(18,18,18,0.04)] transition hover:-translate-y-1 hover:border-accent/50"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent text-ink"><Icon size={18} /></span><div className="mt-5 flex items-center justify-between gap-2"><span className="text-sm font-semibold text-ink">{label}</span><ArrowUpRight size={16} className="text-ink/35 transition group-hover:text-ink" /></div></Link>)}</div> }

function CalendarIcon(props) { return <Clock3 {...props} /> }

export function ProfileSummary() { return <div className="flex items-center gap-4 rounded-2xl border border-ink/10 bg-white p-5 shadow-[0_16px_50px_rgba(18,18,18,0.04)]"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-ink text-lg font-bold text-accent">{memberProfile.initials}</span><div className="min-w-0 flex-1"><p className="text-lg font-bold text-ink">{memberProfile.name}</p><p className="mt-1 text-sm text-ink/45">{memberProfile.memberCode}</p></div><MoreHorizontal size={20} className="text-ink/30" /></div> }

export function AttendanceProgress() { const percentage = Math.round((attendanceSummary.visits / attendanceSummary.monthlyGoal) * 100); return <div className="rounded-2xl border border-ink/10 bg-white p-6 shadow-[0_16px_50px_rgba(18,18,18,0.04)]"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-ink/40">Monthly visits</p><p className="mt-2 text-3xl font-bold text-ink">{attendanceSummary.visits}<span className="text-base font-medium text-ink/35"> / {attendanceSummary.monthlyGoal}</span></p></div><span className="flex h-12 w-12 items-center justify-center rounded-full bg-accent/15 text-ink"><Flame size={21} /></span></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-ink/8"><div className="h-full rounded-full bg-accent" style={{ width: `${percentage}%` }} /></div><p className="mt-3 text-xs text-ink/45">{attendanceSummary.monthlyGoal - attendanceSummary.visits} visits to reach your goal</p></div> }

export function EmptyPage({ icon: Icon = Dumbbell, title, description }) { return <div className="flex min-h-[420px] items-center justify-center rounded-2xl border border-ink/10 bg-white p-8 text-center shadow-[0_16px_50px_rgba(18,18,18,0.04)]"><div><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-accent text-ink"><Icon size={24} /></span><h3 className="mt-6 font-heading text-3xl uppercase text-ink">{title}</h3><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-ink/50">{description}</p></div></div> }
