import { motion } from 'framer-motion'
import { ArrowUpRight, Mail, UsersRound } from 'lucide-react'
import { formatMemberDate, formatMemberDateTime, humanize, membershipLabel } from './memberUtils'

const badge = (value, tone = 'neutral') => <span className={`inline-flex w-fit rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.12em] ${tone === 'active' ? 'border-accent/50 bg-accent/15 text-ink' : tone === 'expired' || tone === 'inactive' || tone === 'suspended' || tone === 'cancelled' ? 'border-amber-500/25 bg-amber-500/10 text-amber-800' : 'border-ink/10 bg-ink/[0.03] text-ink/60'}`}>{humanize(value)}</span>

function ViewButton({ onClick }) { return <button type="button" onClick={onClick} className="inline-flex items-center gap-2 rounded-xl border border-ink/10 px-3 py-2 text-xs font-bold text-ink transition hover:border-accent hover:bg-accent/10" aria-label="View Member details">View <ArrowUpRight size={14} /></button> }

function Membership({ membership }) { return membership ? <div><p className="font-semibold text-ink">{membershipLabel(membership)}</p><div className="mt-1">{badge(membership.status, membership.status)}</div><p className="mt-2 text-xs text-ink/45">{formatMemberDate(membership.starts_at)} – {formatMemberDate(membership.ends_at)}</p></div> : <span className="text-sm text-ink/45">No membership</span> }

function Attendance({ attendance }) { return <div><p className="font-semibold text-ink">{attendance?.total_visits ?? 0} visits</p><p className="mt-1 text-xs text-ink/45">{attendance?.latest_check_in ? formatMemberDateTime(attendance.latest_check_in) : 'No check-in recorded'}</p></div> }

export default function MemberTable({ members, onView }) {
  return <div className="overflow-hidden rounded-2xl border border-ink/10 bg-white shadow-[0_16px_50px_rgba(18,18,18,0.04)]">
    <div className="flex items-center gap-3 border-b border-ink/10 p-5 sm:p-6"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent text-ink"><UsersRound size={19} /></span><div><h2 className="font-heading text-2xl uppercase tracking-wide text-ink sm:text-3xl">Assigned members</h2><p className="mt-1 text-xs text-ink/45">Your current coaching roster.</p></div></div>
    <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] text-left"><thead className="bg-ink/[0.03] text-[11px] uppercase tracking-[0.16em] text-ink/40"><tr><th className="px-6 py-4 font-semibold">Member</th><th className="px-6 py-4 font-semibold">Member code</th><th className="px-6 py-4 font-semibold">Status</th><th className="px-6 py-4 font-semibold">Membership</th><th className="px-6 py-4 font-semibold">Attendance</th><th className="px-6 py-4 text-right font-semibold">Action</th></tr></thead><tbody className="divide-y divide-ink/10">{members.map((member, index) => <motion.tr key={member.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: Math.min(index * 0.035, 0.2) }} className="text-sm transition hover:bg-ink/[0.02]"><td className="px-6 py-4"><p className="font-semibold text-ink">{member.name || 'Member unavailable'}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-ink/45"><Mail size={13} />{member.email || 'Email unavailable'}</p></td><td className="px-6 py-4 text-ink/60">{member.member_code || 'Code unavailable'}</td><td className="px-6 py-4">{badge(member.status, member.status)}</td><td className="px-6 py-4"><Membership membership={member.membership} /></td><td className="px-6 py-4"><Attendance attendance={member.attendance} /></td><td className="px-6 py-4 text-right"><ViewButton onClick={() => onView(member.id)} /></td></motion.tr>)}</tbody></table></div>
    <div className="divide-y divide-ink/10 md:hidden">{members.map((member, index) => <motion.article key={member.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: Math.min(index * 0.04, 0.2) }} className="p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold text-ink">{member.name || 'Member unavailable'}</p><p className="mt-1 truncate text-xs text-ink/45">{member.email || 'Email unavailable'}</p><p className="mt-2 text-xs font-semibold text-ink/55">{member.member_code || 'Code unavailable'}</p></div>{badge(member.status, member.status)}</div><div className="mt-4 grid gap-4 rounded-xl bg-ink/[0.025] p-4 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-ink/35">Membership</p><Membership membership={member.membership} /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-ink/35">Attendance</p><Attendance attendance={member.attendance} /></div></div><div className="mt-4"><ViewButton onClick={() => onView(member.id)} /></div></motion.article>)}</div>
  </div>
}
