import { Bell, Lock, Settings as SettingsIcon } from 'lucide-react'
import { useState } from 'react'
import { PageIntro } from '../components/MemberUI'
import PasswordChangeForm from './PasswordChangeForm'

export default function MemberSettingsPage() {
  const [passwordFormOpen, setPasswordFormOpen] = useState(false)

  return <div className="space-y-8"><PageIntro eyebrow="Preferences" title="Settings" description="Manage your notifications and account preferences." /><div className="max-w-3xl space-y-4"><div className="flex items-center gap-4 rounded-2xl border border-ink/10 bg-white p-6 shadow-[0_16px_50px_rgba(18,18,18,0.04)]"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-accent"><Bell size={19} /></span><div className="flex-1"><p className="text-sm font-bold text-ink">Workout reminders</p><p className="mt-1 text-xs leading-5 text-ink/45">Receive reminders before your scheduled sessions.</p></div><span className="h-6 w-11 shrink-0 rounded-full bg-ink p-1"><span className="block h-4 w-4 translate-x-5 rounded-full bg-accent" /></span></div><div className="rounded-2xl border border-ink/10 bg-white p-6 shadow-[0_16px_50px_rgba(18,18,18,0.04)]"><div className="flex items-start gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-accent"><Lock size={19} /></span><div className="flex-1"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-bold text-ink">Password & security</p><p className="mt-1 text-xs leading-5 text-ink/45">Update your password and review account security.</p></div><button type="button" onClick={() => setPasswordFormOpen((current) => !current)} aria-expanded={passwordFormOpen} className="w-fit shrink-0 rounded-xl border border-ink/10 px-4 py-2 text-xs font-bold text-ink transition hover:border-accent hover:bg-accent">{passwordFormOpen ? 'Close' : 'Manage'}</button></div>{passwordFormOpen && <PasswordChangeForm onCancel={() => setPasswordFormOpen(false)} />}</div></div></div><div className="flex items-center gap-4 rounded-2xl border border-ink/10 bg-white p-6 shadow-[0_16px_50px_rgba(18,18,18,0.04)]"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-accent"><SettingsIcon size={19} /></span><div><p className="text-sm font-bold text-ink">App preferences</p><p className="mt-1 text-xs leading-5 text-ink/45">Your member experience is set to English and Philippine Peso.</p></div></div></div></div>
}
