import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { Mail, MapPin, Phone, RefreshCw, ShieldCheck, UserRound } from 'lucide-react'
import toast from 'react-hot-toast'
import { getMemberProfile, getMemberProfileErrorMessage, saveMemberProfile } from '../../../services/memberProfileService'
import { PageIntro } from '../components/MemberUI'
import LoadingSkeleton from './LoadingSkeleton'
import ProfileErrorState from './ProfileErrorState'
import ProfileForm from './ProfileForm'
import { formatProfileDate, profileInitials, statusClass } from './profileUtils'

const emptyForm = { name: '', email: '', phone: '', address: '', emergency_contact_name: '', emergency_contact_phone: '' }
const errorMessage = (error) => error.status === 401 ? 'Your session has expired. Please sign in again.' : error.status === 403 ? 'You do not have permission to view your profile.' : error.status === 404 ? 'Member profile not found.' : error.isNetworkError ? 'Unable to connect to FitOps. Check your connection and try again.' : getMemberProfileErrorMessage(error, 'Unable to load your profile.')
const formFromProfile = (profile) => ({ name: profile?.name ?? '', email: profile?.email ?? '', phone: profile?.phone ?? '', address: profile?.address ?? '', emergency_contact_name: profile?.emergency_contact_name ?? '', emergency_contact_phone: profile?.emergency_contact_phone ?? '' })

export default function MemberProfilePage() {
  const [profile, setProfile] = useState(null); const [loading, setLoading] = useState(true); const [pageError, setPageError] = useState(''); const [refreshToken, setRefreshToken] = useState(0); const [editing, setEditing] = useState(false); const [form, setForm] = useState(emptyForm); const [errors, setErrors] = useState({}); const [saving, setSaving] = useState(false)
  useEffect(() => { let active = true; setLoading(true); setPageError(''); getMemberProfile().then((value) => { if (active) { setProfile(value); setForm(formFromProfile(value)) } }).catch((error) => { if (active) setPageError(errorMessage(error)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [refreshToken])
  const startEditing = () => { setForm(formFromProfile(profile)); setErrors({}); setEditing(true) }
  const cancelEditing = () => { setForm(formFromProfile(profile)); setErrors({}); setEditing(false) }
  const submit = async (event) => { event.preventDefault(); setSaving(true); setErrors({}); try { const updated = await saveMemberProfile(form); setProfile(updated); setForm(formFromProfile(updated)); setEditing(false); toast.success('Profile updated successfully.') } catch (error) { if (error.status === 422 && Object.keys(error.errors ?? {}).length) { setErrors(error.errors); toast('Please fix the highlighted fields.', { icon: '!' }) } else toast.error(errorMessage(error)) } finally { setSaving(false) } }
  return <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }} className="space-y-8"><PageIntro eyebrow="My account" title="My profile" description="Keep your personal information up to date." />{loading ? <LoadingSkeleton /> : pageError ? <ProfileErrorState message={pageError} onRetry={() => setRefreshToken((value) => value + 1)} /> : profile && !editing ? <div className="grid gap-6 lg:grid-cols-[.55fr_1.45fr]"><div className="rounded-2xl bg-ink p-7 text-white shadow-[0_20px_70px_rgba(18,18,18,0.18)]"><span className="flex h-20 w-20 items-center justify-center rounded-full bg-accent text-2xl font-bold text-ink">{profileInitials(profile)}</span><h3 className="mt-6 font-heading text-3xl uppercase">{profile.name || 'Member'}</h3><p className="mt-2 font-mono text-xs text-white/45">{profile.member_code || 'Member code unavailable'}</p><div className="mt-8 border-t border-white/10 pt-5"><p className="text-xs text-white/40">Member since</p><p className="mt-1 text-sm font-semibold">{formatProfileDate(profile.joined_at)}</p></div></div><div className="rounded-2xl border border-ink/10 bg-white p-6 shadow-[0_16px_50px_rgba(18,18,18,0.04)] sm:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent"><UserRound size={18} /></span><h3 className="font-heading text-3xl uppercase text-ink">Personal details</h3></div><span className={`inline-flex w-fit rounded-full border px-3 py-1 text-[10px] font-bold uppercase tracking-[0.16em] ${statusClass(profile.status)}`}>{profile.status || 'Status unavailable'}</span></div><div className="mt-8 grid gap-5 sm:grid-cols-2"><Detail icon={UserRound} label="Full name" value={profile.name} /><Detail icon={Mail} label="Email address" value={profile.email} /><Detail icon={Phone} label="Phone number" value={profile.phone} /><Detail icon={MapPin} label="Address" value={profile.address} /><Detail label="Emergency contact" value={profile.emergency_contact_name} /><Detail icon={Phone} label="Emergency phone" value={profile.emergency_contact_phone} /></div><button type="button" onClick={startEditing} className="mt-9 inline-flex items-center gap-2 rounded-xl bg-accent px-5 py-3 text-sm font-bold text-ink transition hover:bg-ink hover:text-white">Edit profile</button></div></div> : profile && <ProfileForm form={form} errors={errors} saving={saving} onChange={(event) => { const { name, value } = event.target; setForm((current) => ({ ...current, [name]: value })); setErrors((current) => ({ ...current, [name]: null })) }} onSubmit={submit} onCancel={cancelEditing} />}</motion.div>
}

function Detail({ icon: Icon, label, value }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-ink/40">{label}</p><p className="mt-2 flex items-start gap-2 break-words text-sm font-semibold text-ink">{Icon && <Icon size={15} className="mt-0.5 shrink-0 text-ink/35" />}{value || '—'}</p></div> }
